src/objects/Robinhood_Endpoints__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>stores the different endpoints for the robinhood api</description>
    <fields>
        <fullName>URL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>holds the url for the endpoint</description>
        <label>URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Robinhood Endpoints</label>
</CustomObject>

src/objects/Stock__c.object
<CustomObject>
    <label>Stock</label>
    <nameField>
        <label>Symbol</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Stock_History__c.object
<CustomObject>
    <fields>
        <fullName>Stock__c</fullName>
        <label>Stock</label>
        <referenceTo>Stock__c</referenceTo>
        <relationshipLabel>Stock Historys</relationshipLabel>
        <relationshipName>Stock_Historys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Stock History</label>
    <nameField>
        <displayFormat>SH-{000000000}</displayFormat>
        <label>Stock History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Historys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StockHistoryBatch.cls
public class StockHistoryBatch implements Database.Batchable<sObject>, Database.Stateful, Schedulable, Database.AllowsCallouts {
    private String query;
    private String endpoint;
    private List<Stock_History__c> stockHistoryList = new List<Stock_History__c>();

    public Database.QueryLocator start(Database.BatchableContext BC) {
        query = 'SELECT Id, Name FROM Stock__c';
        endpoint = [SELECT Name, URL__c FROM Robinhood_Endpoints__c WHERE Name = 'Get Quote' LIMIT 1].URL__c;
		return Database.getQueryLocator(query);
	}

   	public void execute(Database.BatchableContext BC, List<Stock__c> scope) {
        Boolean isOpen = RobinhoodHelper.isMarketOpen();
        //iterates through the stocks and creates the stock histories
        for(Stock__c stock : scope){
            if (isOpen){
                HttpResponse response = RobinhoodHelper.getQuote(stock.Name, endpoint);
                RobinhoodHelper.QuoteResponse quote = RobinhoodHelper.makeQuoteResponse(response);
                Stock_History__c stockHistory = RobinhoodHelper.makeStockHistory(quote, stock.Id);
                stockHistoryList.add(stockHistory);
            }
        }
        
        //inserts stock histories
        if (!stockHistoryList.isEmpty()){
            Insert(stockHistoryList);
        }
	}
	
	public void finish(Database.BatchableContext BC) {
        //this is where we will trigger the algorythms
    }

    //scheduler for the batch class
    public void execute(SchedulableContext sc) {
        Id batchJobId = Database.executeBatch(new StockHistoryBatch(), 50);
    }

}